version: "3.7"
networks:
    moneylog-api: {}
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: moneylog
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
          - moneylog-api
        ports:
            - 3306:3306
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/logs:/var/log/mysql
    nginx:
        image: nginx:1.15-alpine
        depends_on:
            - php
        volumes:
            # Comment out the next line in production
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./public:/srv/api/public:ro
        ports:
            - '8081:8081'
            - '8082:8082'
        networks:
            - moneylog-api
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: api_php
        depends_on:
            - db
            - redis
        environment:
            APP_ENV: dev
            PHP_IDE_CONFIG: 'serverName=moneylog'
            PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
            XDEBUG_CONFIG: remote_host=192.168.1.66
        expose:
          - 9000
        networks:
            - moneylog-api
        volumes:
            - ./:/srv/api:rw,cached
    redis:
        image: redis:4-alpine
        networks:
            - moneylog-api
